<?php

/**
 * A Common Cipher Algorithm widely used to
 * Register users in a database.
 * 
 * A cipher Object is first created using a
 * Message to hash, and optionally a given
 * Salt string. In case it is not provided,
 * The module generates it and can return it
 * Using the get_ud_salt_base64() function.
 * Otherwise, the given salt is used to rehash
 * The text key, and that same salt will be 
 * returned.
 *
 * Use the encrypt_key() function to return
 * The final hash.
 *
 * Given a message MSG, this algorithm executes
 * The following procedure:
 * x = system_wide_salt .. MSG ;
 * // Where .. is a concatenation operator.
 * 
 * user_defined_salt is generated by reading
 * /dev/urandom.
 *
 * x ..= binToBase64 ( user_defined_salt ) ;
 * 
 * return hash_token = sha256 ( x ) ;
 *
 * Use the generate_sha256_hmac_key() to return
 * an HMAC hash of the final hash.
 *
 * HMAC can ensure that a hash cannot be
 * exploited even if stolen, by assigning to
 * a given hash one constant secret key.
 *
 * System Administrator must store the secret
 * key in a place where it cannot be possibly 
 * reached in case of a database breach,
 * ie. another server or a different hard disk.
 *
 * @packaged default
 * @author zshulu
 **/

class cipher {

    private $hash_token;
    private $text_key;
    private $iv_size;
    private $user_defined_salt;
    private $reconstruct        = FALSE;
    private $HMAC_KEY           = 'YOUR_TOP_SECRET_KEY_HERE';

    public  $site_wide_defined_salt = 'whodoesnotlovesalt'; // Replace with a salting that suits your taste.

    public function __construct($textkey, $size = 16, $salt = '') {
        $this->iv_size = $size;

        if ($salt == ''){
            $this->user_defined_salt = 
                trim(
                    mcrypt_create_iv ( // Using /dev/urandom by default.
                        $this->iv_size
                    )
                );
            $this->reconstruct = FALSE;
        }
        else {
            $this->user_defined_salt = $salt;
            $this->reconstruct = TRUE;
        }

        $this->text_key = $textkey;
    }

    public function get_ud_salt_base64(){
        return 
            (!$this->reconstruct)?
            base64_encode (
                $this->user_defined_salt  // Transform salt from binary
            ) : $this->user_defined_salt; // Use provided salt as is.
    }

    public function hash_token(){
        $key = $this->site_wide_defined_salt .
            $this->text_key .
            $this->get_ud_salt_base64();

        $this->hash_token = trim (
            hash (
                'sha256',
                $key
            )
        );
        return $this->hash_token;
    }

    public function generate_sha256_hmac_key($i_pad=0x1c, $o_pad=0x2e){

        $key = $this->HMAC_KEY;
        $data = $this->hash_token;

        if(strlen($key) > $this->iv_size)
            $key = hash('sha256', $key);

        $key = str_pad($key, $this->iv_size, chr(0x00), STR_PAD_RIGHT);
        $i_key_pad = $o_key_pad = '';

        for($i = 0; $i < $this->iv_size; $i++){
            $i_key_pad .= chr(
                ord(
                    substr(
                        $key, $i, 1
                    )
                ) ^ $i_pad
            );

            $o_key_pad .= chr(
                ord(
                    substr(
                        $key, $i, 1
                    )
                ) ^ $o_pad
            );
        }

        return hash(
            'sha256',
            $i_key_pad . hash(
                'sha256',
                $o_key_pad . $data
            )
        );

    }

} // END CLASS Cipher

?>
